### ISSUE TITLE
Version v3.0.2 released twice

### ISSUE THREAD

**Issue by perlpunk** [davorg/array-compare#8]
https://metacpan.org/release/DAVECROSS/Array-Compare-v3.0.2
https://metacpan.org/release/MANWAR/Array-Compare-v3.0.2

**Comment by manwar** [comment]
I didn't notice when I released it just before going to TPCiR. Dave Cross gave me permission to release the change, once he approved my changes. I thought everything would work without any issue.

It seems, there is some issues, not sure how to deal with it.
Any suggestions?

Best Regards,
Mohammad S Anwar

**Comment by perlpunk** [comment]
Well, I'm not sure if the behaviour of the indexer is defined if there are two equals versions.
Currently your version seems to be indexed, but still that is confusing.
Imagine someone says "I have a problem with Array::Compare, it does x instead of y", and you ask "What version are you using?" and they say "v3.0.2".

Also there are other tools, for example the Suse Open Build System, where I'm currently maintaining the CPAN mirror directory. Currently it can't handle a new tarball with the same version. So the "new" version will never make it into openSUSE (unless we do it manually): https://build.opensuse.org/package/show/devel:languages:perl:CPAN-A/perl-Array-Compare

If it was my module, I would just upload v3.0.3 as soon as possible.

**Comment by Grinnz** [comment]
I would recommend simply uploading v3.0.3 with no other changes as well.

**Comment by davorg** [comment]
I've just sent version 3.0.3 to CPAN. Hopefully, that will unconfuse everything.

**Comment by davorg** [comment]
@manwar Can you please schedule your 3.0.2 version for deletion?

**Comment by manwar** [comment]
Sure, will do straight away.

**Comment by manwar** [comment]
All done :-)
Scheduled for deletion (due at Thu, 15 Aug 2019 10:40:12 GMT)
